routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BasketController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', [HomeController::class, 'index'])->name('homepage');


Auth::routes();

Route::prefix('product')->name('product.')->group(function () {
    Route::get('/', [ProductController::class, 'index'])->name('all');
    Route::post('/store', [ProductController::class, 'store'])->name('store');
    Route::get('/{product}', [ProductController::class, 'show'])->name('single');
    Route::post('/delete/{product}', [ProductController::class, 'destroy'])->name('delete');
    Route::get('/edit/{product}', [ProductController::class, 'editView'])->name('edit_view');
    Route::post('/edit/{product}', [ProductController::class, 'update'])->name('edit');
//    Route::get('/search',  [ProductController::class, 'search'])->name('search');
});
Route::prefix('/checkout')->name('checkout.')->group(function () {
    Route::get('/', [BasketController::class, 'index'])->name('index');
    Route::post('/', [BasketController::class, 'create'])->middleware('auth')->name('buy');
    Route::post('/{basket}', [BasketController::class, 'destroy'])->name('del');
    Route::get('/check', [BasketController::class, 'wordExport'])->name('check');
    Route::post('/check/edit/{basket}', [BasketController::class, 'editCount'])->name('edit');
});


Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/', [AdminController::class, 'index'])->name('index');
    Route::post('/delete/{user}', [AdminController::class, 'destroy'])->name('delete');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- MDB icon -->
    <link rel="icon" href="{{asset('img/mdb-favicon.ico')}}" type="image/x-icon" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
    />

    <!-- MDB -->
    <link rel="stylesheet" href="{{asset('css/mdb.min.css')}}" />
    <title>FURRY KITTY</title>
</head>
<body>
@include('includes.header')
@section('body')
@show
@include('includes.footer')
</body>
<!-- MDB -->
<script type="text/javascript" src="{{asset('js/mdb.min.js')}}"></script>
<!-- Custom scripts -->
<script type="text/javascript"></script>
</html>

resources/views/layouts/checkout.blade.php
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <title>FURRY KITTY</title>
    <!-- MDB icon -->
    <link rel="icon" href="{{asset('img/mdb-favicon.ico')}}" type="image/x-icon"/>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"/>
    <!-- Google Fonts Roboto -->
    <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
    />

    <link rel="stylesheet" href="https://bootstraptema.ru/plugins/2016/snackbarjs/snackbar.min.css" />

    <!-- MDB -->
    <link rel="stylesheet" href="{{asset('css/mdb.min.css')}}"/>
</head>

<!--Main layout-->
@include('includes.header')


<div class="container" style="margin-top: 10.5em; margin-bottom: 20.5em">
    <div class="row">

        <div class="form-group pull-right">
            <input type="text" class="searchKey form-control" placeholder="Введите товар">
        </div>
        <span class="searchCount pull-right"></span>
        <table class="table table-hover table-bordered results">
            <thead>
            <tr>
                <th class="col-md-5 col-xs-5">Наименование</th>
                <th class="col-md-4 col-xs-4">Цена за шт</th>
                <th class="col-md-3 col-xs-3">Количество</th>
                <th class="col-md-3 col-xs-2">Сохранить</th>
                <th class="col-md-3 col-xs-2">Удалить</th>
            </tr>
            <tr class="warning no-result">
                <td colspan="4"><i class="fa fa-warning"></i> Совпадения не найдены</td>
            </tr>
            </thead>

            <tbody>
            @foreach($items as $item)
                <tr>
                    <th scope="row">{{$item->products->name}}</th>
                    <td>{{$item->products->price}}</td>
                    <form method="post" action="{{route('checkout.edit', ['basket' => $item->id])}}">
                    <td><input value="{{$item->count}}" name="count"></td>
                    <td>

                            @csrf
                            <button class="btn"><i class="fas fa-check flex-row fas fa-times mr-2"></i></button>

                    </td>
                    </form>
                    <td>
                        <form method="post" action="{{route('checkout.del', ['basket' => $item->id])}}">
                            @csrf
                            <button class="btn" data-toggle="snackbar" data-content="Товар успешно удален" data-timeout=9000><i class="fa fa-close flex-row fas fa-times mr-2"></i></button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <span class="text-success">Итог (RUB)</span>
        <strong class="text-success">{{$items->sum(function ($item){
             return $item->products->price * $item->count;})}}</strong>
        <form class="card-body" method="GET" action="{{route('checkout.check')}}">
            @csrf
            <a href="{{route('checkout.check')}}" class="btn btn-danger btn-lg btn-block {{$items->count() == 0 ? 'disabled' : ''}}"
               data-toggle="snackbar" data-content="Товар успешно оплачен" data-timeout=9000
               type="submit">Оплатить заказ</a>
        </form>
    </div>
</div>



@include('includes.footer')
</main>
<!--Main layout-->

<!-- MDB -->
<script type="text/javascript" src="{{asset('js/mdb.min.js')}}"></script>
<!-- Custom scripts -->
<script type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

<script src="https://bootstraptema.ru/plugins/jquery/jquery-1.11.3.min.js"></script>
<script src="https://bootstraptema.ru/plugins/2016/snackbarjs/snackbar.min.js"></script>
<style>
    /* Стили подсказки по умолчанию */
    .snackbar {
        background-color: #F93154;
        color: #FFFFFF;
        font-size: 14px;
        border-radius: 2px;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
        height: 0;
        -moz-transition: -moz-transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s, padding 0 linear 0.2s, height 0 linear 0.2s;
        -webkit-transition: -webkit-transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s, padding 0 linear 0.2s, height 0 linear 0.2s;
        transition: transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s, padding 0 linear 0.2s, height 0 linear 0.2s;
        -moz-transform: translateY(200%);
        -webkit-transform: translateY(200%);
        transform: translateY(200%);
    }
    .snackbar.snackbar-opened {
        padding: 14px 15px;
        margin-bottom: 20px;
        height: auto;
        -moz-transition: -moz-transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s;
        -webkit-transition: -webkit-transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s;
        transition: transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s, height 0 linear 0.2s;
        -moz-transform: none;
        -webkit-transform: none;
        transform: none;
    }
    .snackbar.toast {
        border-radius: 200px;
    }
</style>

<style>
    .results tr[visible='false'],
    .no-result {
        display: none;
    }

    .results tr[visible='true'] {
        display: table-row;
    }

    .searchCount {
        padding: 8px;
        color: #ccc;
    }
</style>

<script>
    function createExpr(arr) {
        var index = 0;
        var expr = [":containsiAND('" + arr[0] + "')"];
        for (var i = 1; i < arr.length; i++) {
            if (arr[i] === 'AND') {
                expr[index] += ":containsiAND('" + arr[i + 1] + "')";
                i++;
            } else if (arr[i] === 'OR') {
                index++;
                expr[index] = ":containsiOR('" + arr[i + 1] + "')";
                i++;
            }
        }
        return expr;
    }

    $(document).ready(function () {

        $(".searchKey").keyup(function () {
            var searchTerm = $(".searchKey").val().replace(/["']/g, "");
            var arr = searchTerm.split(/(AND|OR)/);
            var exprs = createExpr(arr);
            var searchSplit = searchTerm.replace(/AND/g, "'):containsiAND('").replace(/OR/g, "'):containsiOR('");

            $.extend($.expr[':'], {
                'containsiAND': function (element, i, match, array) {
                    return (element.textContent || element.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
                }
            });

            $('.results tbody tr').attr('visible', 'false');
            for (var expr in exprs) {
                $(".results tbody tr" + exprs[expr]).each(function (e) {
                    $(this).attr('visible', 'true');
                });
            }

            var searchCount = $('.results tbody tr[visible="true"]').length;

            $('.searchCount').text('Найдено совпадений ' + searchCount);
            if (searchCount == '0') {
                $('.no-result').show();
            } else {
                $('.no-result').hide();
            }
            if ($('.searchKey').val().length == 0) {
                $('.searchCount').hide();
            } else {
                $('.searchCount').show();
            }
        });
    });
</script>

resources/views/layouts/edit_product.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Редактирование товара</title>
    <!-- MDB icon -->
    <link rel="icon" href="{{asset('img/mdb-favicon.ico')}}" type="image/x-icon" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
    />

    <link rel="stylesheet" href="https://bootstraptema.ru/plugins/2016/snackbarjs/snackbar.min.css" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
    <!-- MDB -->
    <link rel="stylesheet" href="{{asset('css/mdb.min.css')}}" />
</head>
<body>
@include('includes.header')
<!-- Edit Modal -->
<div class="modal-dialog modal-lg  modal-dialog-centered" style="margin-top: 10.5em; margin-bottom: 25.5em">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Изменение</h5>
        </div>
        <form enctype='multipart/form-data' method="POST" action="{{route('product.edit', ['product' => $product->id])}}">
            @csrf
            <div class="modal-body">
                <div class="form-outline mb-3">
                    <input type="text" id="name" name="name" class="form-control" value="{{$product->name}}"/>
                    <label class="form-label" for="name">Название</label>
                </div>
                <div class="form-group quantity mb-3">
                    <select name="category" class="form-control">
                        <option @if($product->category == "Собаки") selected="selected" @endif>Собаки</option>
                        <option @if($product->category == "Кошки") selected="selected" @endif>Кошки</option>
                        <option @if($product->category == "Грызуны") selected="selected" @endif>Грызуны</option>
                        <option @if($product->category == "Пернатые") selected="selected" @endif>Пернатые</option>
                        <option @if($product->category == "Рыбы") selected="selected" @endif>Рыбы</option>
                        <option @if($product->category == "Рептилии") selected="selected" @endif>Рептилии</option>
                    </select>
                </div>
                <div class="form-outline mb-3">
                    <input type="text" id="price" name="price" class="form-control" value="{{$product->price}}"/>
                    <label class="form-label" for="price">Цена</label>
                </div>
                <div class="form-outline mb-3">
                    <input type="text" id="old_price" name="old_price" class="form-control" value="{{$product->old_price}}"/>
                    <label class="form-label" for="old_price">Старая цена (если есть)</label>
                </div>
                <div class="form-outline mb-3">
                    <textarea class="form-control" id="description" name="description" rows="4">{{$product->description}}</textarea>
                    <label class="form-label" for="description">Описание</label>
                </div>

                <div class="form-outline mb-3">
                    <input type="text" id="weight" name="weight" class="form-control" value="{{$product->weight}}"/>
                    <label class="form-label" for="weight">Вес</label>
                </div>

                <input type="file" class="form-control" id="image" name="image" />
            </div>
            <div class="modal-footer">
                <a href="{{route('product.all')}}" type="button" class="btn btn-outline-primary" data-mdb-dismiss="modal">
                    Закрыть
                </a>
                <button type="submit" class="btn btn-danger"
                        data-toggle="snackbar" data-content="Товар успешно изменен" data-timeout=9000
                >Сохранить изменения</button>
            </div>
        </form>
    </div>
</div>
@include('includes.footer')

<!-- MDB -->
<script type="text/javascript" src="{{asset('js/mdb.min.js')}}"></script>
<!-- Custom scripts -->
<script type="text/javascript"></script>
<script src="https://bootstraptema.ru/plugins/jquery/jquery-1.11.3.min.js"></script>
<script src="https://bootstraptema.ru/plugins/2016/snackbarjs/snackbar.min.js"></script>
<style>
    /* Стили подсказки по умолчанию */
    .snackbar {
        background-color: #F93154;
        color: #FFFFFF;
        font-size: 14px;
        border-radius: 2px;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
        height: 0;
        -moz-transition: -moz-transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s, padding 0 linear 0.2s, height 0 linear 0.2s;
        -webkit-transition: -webkit-transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s, padding 0 linear 0.2s, height 0 linear 0.2s;
        transition: transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s, padding 0 linear 0.2s, height 0 linear 0.2s;
        -moz-transform: translateY(200%);
        -webkit-transform: translateY(200%);
        transform: translateY(200%);
    }
    .snackbar.snackbar-opened {
        padding: 14px 15px;
        margin-bottom: 20px;
        height: auto;
        -moz-transition: -moz-transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s;
        -webkit-transition: -webkit-transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s;
        transition: transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s, height 0 linear 0.2s;
        -moz-transform: none;
        -webkit-transform: none;
        transform: none;
    }
    .snackbar.toast {
        border-radius: 200px;
    }
</style>
</body>
</html>

resources/views/layouts/product.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Товары</title>
    <!-- MDB icon -->
    <link rel="icon" href="{{asset('img/mdb-favicon.ico')}}" type="image/x-icon" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
    />

    <link rel="stylesheet" href="https://bootstraptema.ru/plugins/2016/snackbarjs/snackbar.min.css" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
    <!-- MDB -->
    <link rel="stylesheet" href="{{asset('css/mdb.min.css')}}" />
</head>
<body>
@include('includes.header')


<!-- Card -->
<div class="container">


    <div class="row gx-5 justify-content-center">
        <table class="table table-hover table-bordered results">

            @foreach($items as $item)
            <div class="col-lg-3 col-md-6 mt-5">
                        <div class="card position-relative position-relative-example" style="width: 18rem">
                            <div class="position-absolute top-5 end-0 rounded text-white bg-color bg-primary w-50 text-center">{{$item->category}}</div>
{{--                            <img--}}
{{--                                src="/img/{{$item->image}}"--}}
{{--                                class="card-img-top"--}}
{{--                                alt="..."--}}
{{--                            />--}}
                            <img src="{{$item->image_url}}" style="overflow:hidden; height:320px; width:170px; border-radius:10%; margin: 20%" class="card-img-top"/>
                            <div class="card-body">
                                <h5><a href="{{route('product.single',['product'=>$item->id])}}" class="d-inline-block card-title text-truncate text-dark" style="max-width: 250px">{{$item->name}}</a></h5>
                                <p class="card-text text-truncate" style="max-width: 350px">
                                    {{$item->description}}
                                </p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Вес: {{$item->weight}} г.</li>
                                @if(is_null($item->old_price))
                                    <li class="list-group-item">Цена: {{$item->price}} руб.</li>
                                @else
                                    <li class="list-group-item">Цена: {{$item->price}} руб.</li>
                                    <li class="list-group-item g">Старая цена: <a class="text-decoration-line-through text-warning">{{$item->old_price}} руб.</a></li>

                                @endif

                            </ul>

                            <div class="card-body">
                                <form method="post" action="{{route('checkout.buy')}}">
                                    @csrf
                                    <input type="hidden" name="product_id" value="{{$item->id}}">
{{--                                    <input type="hidden" name="user_id" value="{{auth()->user()->id}}">--}}
                                    <input type="hidden" name="count" value="1">
                                <button data-toggle="snackbar" data-content="Товар успешно добавлен в корзину" data-timeout=9000
                                        type="submit" class="btn btn-outline-danger mb-2 w-100 hover-shadow {{auth()->user() == null? "disabled" : ""}}" data-mdb-ripple-color="#000000">
                                        Добавить в корзину </button>
                                </form>
                                <!-- Button add modal -->

{{--                                {{dd(is_null(auth()->user()) ?: auth()->user())}}--}}
                                @if(is_null(auth()->user()) ? false : auth()->user()->IsAdmin)
                                <form method="post" action="{{route('product.delete', ['product'=>$item->id])}}">
                                    @csrf
                                    <a class="btn btn-outline-primary mb-2"
                                       href="{{route('product.edit_view', ['product' => $item->id])}}">
                                        <i class="far fa-edit"></i>
                                    </a>
                                    <button type="button submit" class="btn btn-outline-primary mb-2" data-mdb-ripple-color="#000000"
                                            data-toggle="snackbar" data-content="Товар успешно удален" data-timeout=9000>
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </form>
                                @endif

                            </div>
                        </div>
                </div>
            @endforeach
        </table>
<hr class="my-5">
        </div>
</div>
<!-- Padding -->

<nav class="d-flex justify-content-center wow fadeIn">
    <ul class="pagination pg-blue">
        <li class="page-item">
            <a href="" class="page-link" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        @for($i=1;$i<=$items->lastPage();$i++)
        <li class="page-item @if($i == $items->currentPage()) active @endif">
            <a href="{{url()->current()."?page=".$i}}" class="page-link" aria-label="Previous">
                <span aria-hidden="true">{{$i}}</span>
            </a>
        </li>
        @endfor
        <li class="page-item">
            <a href="" class="page-link" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>




<!-- MDB -->
<script type="text/javascript" src="{{asset('js/mdb.min.js')}}"></script>
<!-- Custom scripts -->
<script type="text/javascript"></script>

<script src="https://bootstraptema.ru/plugins/jquery/jquery-1.11.3.min.js"></script>
<script src="https://bootstraptema.ru/plugins/2016/snackbarjs/snackbar.min.js"></script>
<style>
    /* Стили подсказки по умолчанию */
    .snackbar {
        background-color: #F93154;
        color: #FFFFFF;
        font-size: 14px;
        border-radius: 2px;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
        height: 0;
        -moz-transition: -moz-transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s, padding 0 linear 0.2s, height 0 linear 0.2s;
        -webkit-transition: -webkit-transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s, padding 0 linear 0.2s, height 0 linear 0.2s;
        transition: transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s, padding 0 linear 0.2s, height 0 linear 0.2s;
        -moz-transform: translateY(200%);
        -webkit-transform: translateY(200%);
        transform: translateY(200%);
    }
    .snackbar.snackbar-opened {
        padding: 14px 15px;
        margin-bottom: 20px;
        height: auto;
        -moz-transition: -moz-transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s;
        -webkit-transition: -webkit-transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s;
        transition: transform 0.2s ease-in-out, opacity 0.2s ease-in, height 0 linear 0.2s, height 0 linear 0.2s;
        -moz-transform: none;
        -webkit-transform: none;
        transform: none;
    }
    .snackbar.toast {
        border-radius: 200px;
    }
</style>







@include('includes.footer')
</body>
</html>